# Generated by Django 5.1.4 on 2025-01-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_centers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalcenter",
            name="contracted_health_institutions",
        ),
        migrations.RemoveField(
            model_name="medicalcenter",
            name="Procedure",
        ),
        migrations.RemoveField(
            model_name="medicalcenter",
            name="specialities",
        ),
        migrations.RemoveField(
            model_name="medicalcentervideos",
            name="medical_center",
        ),
        migrations.RemoveField(
            model_name="medicalcenterphotos",
            name="medical_center",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="HealthInstitutions",
        ),
        migrations.DeleteModel(
            name="Procedure",
        ),
        migrations.DeleteModel(
            name="Speciality",
        ),
        migrations.DeleteModel(
            name="MedicalCenterVideos",
        ),
        migrations.DeleteModel(
            name="MedicalCenter",
        ),
        migrations.DeleteModel(
            name="MedicalCenterPhotos",
        ),
    ]
