# Generated by Django 5.1.4 on 2025-01-10 14:35

import django.db.models.deletion
import markdownx.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "medical_centers",
            "0002_remove_medicalcenter_contracted_health_institutions_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthInstitutions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("center_name", models.CharField(max_length=200, null=True)),
                (
                    "center_type",
                    models.CharField(
                        choices=[
                            ("Hosp", "Hospital"),
                            ("Clin", "Clinic"),
                            ("MedCent", "Medical Center"),
                            ("UniHosp", "University Hospital"),
                            ("DentClin", "Dental Clinic"),
                            ("UniMedCent", "University Medical Center"),
                            ("Cent", "Center"),
                            ("HospGrp", "Hospital Groups"),
                            ("RehabCent", "Rehabilitation Center"),
                            ("ChildCent", "Children's Hospital"),
                        ],
                        default="Hosp",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("IST", "İSTANBUL"),
                            ("ANK", "ANKARA"),
                            ("IZ", "İZMİR"),
                            ("SM", "SAMSUN"),
                            ("BRS", "BURSA"),
                            ("TRZ", "TRABZON"),
                            ("MER", "MERSİN"),
                            ("ADA", "ADANA"),
                            ("HAT", "HATAY"),
                            ("KON", "KONYA"),
                            ("KRM", "KARAMAN"),
                            ("GAZ", "GAZİANTEP"),
                            ("KCE", "KOCAELİ"),
                            ("AYD", "AYDIN"),
                            ("ERZ", "ERZURUM"),
                        ],
                        default="IST",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "contact_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, null=True, region=None
                    ),
                ),
                ("mail_address", models.EmailField(max_length=100, null=True)),
                ("web_site", models.URLField(null=True)),
                ("preview_text", markdownx.models.MarkdownxField(null=True)),
                ("overview_text", markdownx.models.MarkdownxField(null=True)),
                (
                    "contracted_health_institutions",
                    models.ManyToManyField(
                        related_name="medical_centers_health_inst",
                        to="medical_centers.healthinstitutions",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_center",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "procedure",
                    models.ManyToManyField(
                        related_name="medical_centers_procedure",
                        to="medical_centers.procedure",
                    ),
                ),
                (
                    "specialities",
                    models.ManyToManyField(
                        related_name="medical_centers_specialities",
                        to="medical_centers.speciality",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("major", models.CharField(max_length=100)),
                ("minor", models.CharField(max_length=100)),
                (
                    "related_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="medical_centers.medicalcenter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalCenterPhotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="medical_center/photos/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medical_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_center_photos",
                        to="medical_centers.medicalcenter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalCenterVideos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_name", models.CharField(max_length=100)),
                ("video_link", models.URLField(max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medical_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_center_videos",
                        to="medical_centers.medicalcenter",
                    ),
                ),
            ],
        ),
    ]
