# Generated by Django 5.1.4 on 2025-01-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_centers", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicalcenter",
            old_name="procedure",
            new_name="procedures",
        ),
    ]
