# Generated by Django 5.1.4 on 2025-01-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_centers", "0007_alter_doctor_minor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="title",
            field=models.CharField(
                choices=[
                    ("Dr.", "Doctor"),
                    ("Assoc. Dr.", "Associated Doctor"),
                    ("Asst. Dr.", "Assistant Professor"),
                ],
                default="Dr.",
                max_length=100,
                null=True,
            ),
        ),
    ]
