# Generated by Django 5.1.4 on 2025-01-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_centers", "0009_alter_doctor_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="procedure",
            old_name="speciality_code",
            new_name="speciality_id",
        ),
    ]
