# Generated by Django 5.1.4 on 2025-01-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_centers", "0011_rename_speciality_id_procedure_speciality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalcenterphotos",
            name="image_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="medicalcentervideos",
            name="video_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
