# Generated by Django 5.1.4 on 2025-01-16 14:01

import medical_centers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_centers", "0012_alter_medicalcenterphotos_image_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalcenterphotos",
            name="image",
            field=models.ImageField(
                upload_to=medical_centers.models.medical_center_photo_upload_path
            ),
        ),
    ]
