# Generated by Django 5.1.4 on 2025-01-08 12:41

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="city",
        ),
        migrations.AlterField(
            model_name="patient",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
