# Generated by Django 5.1.4 on 2025-01-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0002_remove_patient_city_alter_patient_country"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
