# Generated by Django 5.1.4 on 2025-01-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0004_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
