# Generated by Django 5.1.4 on 2025-01-20 11:46

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("medical_centers", "0014_alter_medicalcenter_city"),
        ("patient", "0007_alter_patient_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalCenterRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("w", "woman"), ("m", "man")],
                        default="w",
                        max_length=1,
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("disease_history", models.TextField(blank=True, null=True)),
                ("previous_disease", models.TextField(blank=True, null=True)),
                ("previous_surgery", models.TextField(blank=True, null=True)),
                ("previous_treatment", models.TextField(blank=True, null=True)),
                ("other_comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities_light.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cities_light.country",
                    ),
                ),
                (
                    "medical_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="medical_centers.medicalcenter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="patient.patient",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="medical_centers.procedure",
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="medical_centers.speciality",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalCenterRequestFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="medical_center_requests/files/")),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="patient.medicalcenterrequest",
                    ),
                ),
            ],
        ),
    ]
