# Generated by Django 5.1.4 on 2025-01-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="City",
            new_name="Destination",
        ),
    ]
